// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzq9ukRMxpukFLufjthQ8I6vKV-urjkik',
    appId: '1:254102908618:web:66018ae50b5c640c058e33',
    messagingSenderId: '254102908618',
    projectId: 'e-commerce-app-f30a9',
    authDomain: 'e-commerce-app-f30a9.firebaseapp.com',
    storageBucket: 'e-commerce-app-f30a9.appspot.com',
    measurementId: 'G-SMWXMXHHGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe6ObC9YXqH9ZUptKVBQuW7tqCnFhXysk',
    appId: '1:254102908618:android:78e5f141020c933b058e33',
    messagingSenderId: '254102908618',
    projectId: 'e-commerce-app-f30a9',
    storageBucket: 'e-commerce-app-f30a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC31fO2Rmkts-6dIqFZwhOiGRgp4XJrqBo',
    appId: '1:254102908618:ios:90887901bd541461058e33',
    messagingSenderId: '254102908618',
    projectId: 'e-commerce-app-f30a9',
    storageBucket: 'e-commerce-app-f30a9.appspot.com',
    iosBundleId: 'com.example.eCommerceAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC31fO2Rmkts-6dIqFZwhOiGRgp4XJrqBo',
    appId: '1:254102908618:ios:90887901bd541461058e33',
    messagingSenderId: '254102908618',
    projectId: 'e-commerce-app-f30a9',
    storageBucket: 'e-commerce-app-f30a9.appspot.com',
    iosBundleId: 'com.example.eCommerceAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzq9ukRMxpukFLufjthQ8I6vKV-urjkik',
    appId: '1:254102908618:web:902c027f3614efd2058e33',
    messagingSenderId: '254102908618',
    projectId: 'e-commerce-app-f30a9',
    authDomain: 'e-commerce-app-f30a9.firebaseapp.com',
    storageBucket: 'e-commerce-app-f30a9.appspot.com',
    measurementId: 'G-MGCNXYGL8T',
  );
}
